import React from 'react';
import { RichTextField, TextField, EmailField, DateField, NumberField, UrlField, BooleanField, ImageField, SelectField, ReferenceField } from 'react-admin';

export default {
	field2element: (field) => {
		switch (Number(field.uitype)) {
			case 21: // TextBox small
			case 19: // TextBox big
				return <RichTextField key={field.name} label={field.label} source={field.name} />;
			case 5: // Date
				return <DateField key={field.name} label={field.label} source={field.name} />;
			case 50: // DateTime
				return <DateField key={field.name} label={field.label} source={field.name} showTime />;
			case 7: // Number
				return <NumberField key={field.name} label={field.label} source={field.name} />;
			case 9: // Percentage
				return <NumberField key={field.name} label={field.label} source={field.name} options={{ style: 'percent' }} />;
			case 71: // Currency
				return <NumberField key={field.name} label={field.label} source={field.name} options={{ style: 'currency', currency: 'EUR' }} />;
			case 10: // Module Relation
			case 101: // User Relation
				let eidfield = window.coreBOS.Describe[field.type.refersTo[0]].labelFields.split(',');
				return <ReferenceField key={field.name} label={field.label} source={field.name} reference={field.type.refersTo[0].toLowerCase()} link="show" >
						<TextField key={'ref'+field.name} source={eidfield[0]} />
					</ReferenceField>;
			case 53: // User Relation: Assigned To
				return <ReferenceField key={field.name} label={field.label} source={field.name} reference="users" >
						<TextField key={'ref'+field.name} source="first_name" />
					</ReferenceField>;
			case 13: // Email
				return <EmailField key={field.name} label={field.label} source={field.name} />;
			case 17: // URL
				return <UrlField key={field.name} label={field.label} source={field.name} />;
			case 56: // Checkbox
				return <BooleanField key={field.name} label={field.label} source={field.name} />;
			case 69: // Image
				return <ImageField key={field.name} label={field.label} source={field.name} />;
			case 15: // SelectWithRole,
			case 16: // Select,
			case 1613: // SelectModules,
			case 1024: // SelectRoles,
			case 33: // SelectMultiple,
			case 3313: // SelectModulesMultiple,
				return <SelectField key={field.name} label={field.label} source={field.name} choices={field.type.picklistValues} optionText="value" optionValue="label" />;
			case 1:
			case 11: // Phone
			case 14: // Time
			case 85: // Skype
			// 4: mod_alert_arr.AutoGenerated,
			default:
				return <TextField key={field.name} label={field.label} source={field.name} />;
		}
	}
};
